version: "3.9"

services:
  IoTCosmosDb:
    image: "mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator"
    ports: 
        - 8081:8081
        - 10251:10251
        - 10252:10252
        - 10253:10253
        - 10254:10254
    tty: true
    restart: always
    mem_limit: 2G
    cpu_count: 2
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=10
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=192.168.1.102
    volumes:
      - cosmosdb_data:/data/db

volumes: 
  cosmosdb_data: